// <auto-generated />
using System;
using Blinks.Repo;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Blinks.Repo.Migrations
{
    [DbContext(typeof(PlanilhaContexto))]
    [Migration("20201216044832_tres")]
    partial class tres
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("Blinks.Dominio.Planilha", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("campaign_id")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("campaign_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("clicks")
                        .HasColumnType("int");

                    b.Property<string>("client_id")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("client_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("date")
                        .HasColumnType("datetime2");

                    b.Property<int>("impressions")
                        .HasColumnType("int");

                    b.Property<float>("investment")
                        .HasColumnType("real");

                    b.Property<string>("media")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Planilhas");
                });
#pragma warning restore 612, 618
        }
    }
}
